### ISSUE TITLE
Suggestion to Add to AAPB Topical Genre

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#10]
Journalism or Media

I just cataloged a program called Privacy vs The Press that was about ethical issues in journalism and the freedom of the press. It doesn't really fit into News, and Film and Television would leave out print journalism. Right now, I've put it under Social Issues, but I think having a topic for journalism/media would be helpful.

cpb-aacip/46-78tb314j

**Comment by sroosa** [comment]
Journalism has been added to the AAPB Topical Genre vocab.
