### ISSUE TITLE
Format Genre for Radio/Music Show

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#12]
This is an episode of a radio series that features music interspersed with a host talking about aspects of the history and culture of the country of Dominica. It doesn't quite fit into any of the current format genres.

cpb-aacip/305-40ksn418

**Comment by sroosa** [comment]
For any programming with recorded music (that is the host or DJ playing music from tapes, cds, mp3s, etc.), add the new Genre Format term: Recorded Music. If there is more content than just the recorded music, you can add additional terms that fit that content. 

So in this case, you would have Recorded Music, History, and maybe Documentary, if you think the history/culture sections warrant that term.
