### ISSUE TITLE
Appropriate Genre Topic?

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#15]
cpb-aacip/305-42n5tg9b
This is an interview about ESP and parapsychology with a woman who is a psychic and lecturer at the University of Massachusetts. What genre topic would be most appropriate?

**Comment by sroosa** [comment]
Sorry it took me so long to answer this. Since we don't really have a lot of content about this, you can just use a Format Genre and no Topical Genre.
