### ISSUE TITLE
Comedic genres

### ISSUE THREAD

**Issue by ericalleeman** [sroosa/AAPB_Cataloging#18]
I just cataloged an asset ( cpb-aacip/380-77fqzdt7 ) that is musical political satire in the form of a skits/sketches. Is the format genre Stand-Up appropriate? Also, I think a topical genre for Comedy or Humor would be useful.

**Comment by sroosa** [comment]
I just added Humor as a Topical Genre. For the format genre, I would use either Peformance in a Studio or Performance for a Live Audience, depending on how it was recorded.
