### ISSUE TITLE
Two Issues with Contributor Field

### ISSUE THREAD

**Issue by careymacd92** [sroosa/AAPB_Cataloging#19]
I think the first reporter's name in the WGBH asset I worked on the first day is Lisa Freud, but no Google search result is verifying that name as being associated with WGBH. 
Also, not all of the roles of the Contributors are showing next to the names on the catalog record even though I have selected their roles in the drop-down box when editing -- not sure if that is normal. Thanks!
cpb-aacip/15-77fqzmpj

**Comment by sroosa** [comment]
When you save them correctly in the drop down menu, then you're good. Like I said before the catalog record displays the data kind of incorrectly. So it will only use each creator/contributor role once, and sometimes it will even look as if the wrong contributor/creator role is matched up with a name, but that's not how it is in the backend database, or how it will appear when the data gets refreshed to populate the public website. It's just one of those quirks we have to deal with. 

If you can't find someone through a google search, just go with what you hear.
