### ISSUE TITLE
Role term for Choreographer

### ISSUE THREAD

**Issue by ericalleeman** [sroosa/AAPB_Cataloging#20]
For ballet and other dance performances, a choreographer is usually named, and having them in a creator or contributor field would be useful.

**Comment by sroosa** [comment]
Added to the contributor role controlled vocab!

**Comment by ericalleeman** [comment]
Choreographer isn't showing up in the drop down menu for contributor role in the AMS.

**Comment by sroosa** [comment]
Oh no! I may have forgotten to tell our programmer to add it... Doing that now. Oops!
