### ISSUE TITLE
Roles for Multiple Contributors

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#3]
I noticed in this record that the Interviewee role types for the second and third contributors (Julia Alvarez, Lawrence McCrorey) are not saving.
cpb-aacip/46-61rfjdrs

Also in this record: cpb-aacip/46-698671px

**Comment by sroosa** [comment]
Yes, that was a problem that we were actually just able to fix. Try again, and let me know if it's still an issue.

**Comment by aabn** [comment]
I checked in these records, and the contributor role types are working.
