### ISSUE TITLE
Roles for Multiple Contributors

### ISSUE THREAD

**Issue by samanthaq25** [sroosa/AAPB_Cataloging#4]
I'm having trouble saving all the different roles of the contributor for cpb-aacip/147-085hqcwn. All the roles keep defaulting to the role of the first contributor (host), but obviously, they aren't all hosts. I tried saving and changing repeatedly and even logging out. Nothing seems to work.

**Comment by sroosa** [comment]
Hmm... I'll look into this with our programmer.

**Comment by samanthaq25** [comment]
Now, it's also acting weird with multiple creators as well. Like for another record, cpb-aacip/147-322bvt64, everyone is being listed as an executive producer, because the first person on the list is one. Then the contributors for that same records are inaccurate because the AMS keeps changing Goofer Abernathy's role from performer to host. So if you could look over the creator drop-downs and how they are save with your programmers as well, that would be great. Thanks!

**Comment by aabn** [comment]
I'm also experiencing issues with roles for multiple creators. The roles for additional creators are being overwritten to match the role of the first creator. Examples: cpb-aacip/46-18rbp24r, cpb-aacip/111-10jsxpp1, cpb-aacip/46-698671px

**Comment by ericalleeman** [comment]
When assigning affiliations to contributors, the AMS removed them from the people they are associated with and put them with the first contributors listed. See cpb-aacip/106-31cjt1ck 

I'm pretty sure this is ultimately the same problem, or very similar, to both this issue and the issues with multiple genres.

**Comment by sroosa** [comment]
Kevin fixed this.
