### ISSUE TITLE
Multiple Topical Genres?

### ISSUE THREAD

**Issue by aabn** [sroosa/AAPB_Cataloging#6]
Can we assign multiple topical genres? I have three episodes of a program in one file, and each interview is about a different topic. I can add multiple topical genres, but after I save the record, the genre source disappears on the additional fields.
cpb-aacip/46-44pk0tg1

**Comment by ericalleeman** [comment]
I am having the exact same problem. It has no issue with keeping Format and Topical differentiated, but on a second Topical genre, the source is deleted when the changes are saved. The record I was working on: cpb-aacip/111-30prrbg8

**Comment by sroosa** [comment]
You can use multiple topical and format genres. Continue to add them, even though the source is disappearing, and note this issue number in the cataloging progress sheet. I'm really sorry the edit function is having all of these issue. So annoying!

**Comment by ericalleeman** [comment]
I just did a record that had two of each type of genre, and it did yet another weird thing to the source notation. cpb-aacip/426-93ttf7c8

It seems like it's only allowing one genre listing from each vocabulary, but it's also ignoring the ones you assign. It just gives the first one listed Format and the second one listed Topical, even though in this case the first two listed are both Format. The following two are both Topical, but their sources have been deleted.

**Comment by sroosa** [comment]
Yeah, that is some old display logic from the original code that we tried to fix. Obviously we need to work on it some more. Basically the system just looks for the next unique source, and displays that, which is why it would display Topical even though the first two are both Format.

**Comment by ericalleeman** [comment]
Multiple annotations will also not allow different annotation types.
cpb-aacip/426-75dbs2p7

**Comment by sroosa** [comment]
fixed now- just don't worry about how it looks in the record view. If it's right when you enter in the edit view and hit save, then it will be correct in the database.
