### ISSUE TITLE
Persons with multiple roles

### ISSUE THREAD

**Issue by ericalleeman** [sroosa/AAPB_Cataloging#8]
In the record for cpb-aacip/426-65v6x3x7, the same two people acted as producers and writers, and one of them also acted as director. It doesn't seem to want to allow multiple roles; it changed it to one person as producer and the other as writer and no director listed. For reference, this is how the responsibilities break down for that asset: 
Producer
Reynolds, Claire and Frankel, Seth

Director
Frankel, Seth

Writer
Claire and Seth again

**Comment by sroosa** [comment]
This is another thing I'll have to bring to our programmer. I'll get back with either a work around or when the problem with the AMS is fixed.

**Comment by sroosa** [comment]
List each creator/role pair separately. So repeat the people as many times as they have roles.
