### ISSUE TITLE
Almost identical assets

### ISSUE THREAD

**Issue by ericalleeman** [sroosa/AAPB_Cataloging#9]
I cataloged cpb-aacip/426-93ttf7bj earlier today. Another asset, cpb-aacip/426-93gxdbhk, is the same program and is identical in every way (that I can tell) except for the images used in the opening and closing credits. What should I do?

**Comment by sroosa** [comment]
Identical assets do not need to be cataloged twice. Mark in the Cataloging Progress spreadsheet that the second asset is identical to the first, and then don't catalog it.
